name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out pull request
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          github_access_token: ${{ github.token }}

          extra_nix_config: |
            extra-substituters = https://vicinae.cachix.org
            extra-trusted-public-keys = vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc=

      - name: Check flake and build package
        run: >-
          nix flake check
          --no-update-lock-file
          # Do not accept cache configuration supplied by the pull request's flake.
          --option accept-flake-config false
          --print-build-logs
